#
server:
  ssl:
    enabled: true
    key-alias: thrthn-ssl
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: Store1!
#    key-store-provider: 
#  port: 8888
  port: 8443
  servlet:
    context-path: /thrthn

#
spring:
  messages:
#    basename: messages
#    encoding: UTF-8
    fallback-to-system-locale: false
    cache-duration: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thrthn
    username: thrthn
    password: thrthn
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  security:
    user:
      name: jynius
      password: jynius

  mvc:
    format:
      time: HH:mm:ss
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd

  thymeleaf:
    encoding: UTF-8
    check-template: true
    check-template-location: true
    prefix: /WEB-INF/template/
    suffix: .html
    mode: HTML5
    cache: false
    enable-spring-el-compiler: true

#
debug: true
logging:
  config: classpath:logback.xml
  level:
    ROOT: debug
